[package]
name = "threads"
version = "0.1.0"
authors = ["grindlemire <grindlemire@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "1.11.0"
log = "0.4.11"
clap = "3.0.0-beta.2"

